gc-activities jobs fails with missing permissions
```
error: deployments.apps "prow-build" is forbidden: User "system:serviceaccount:jx:jenkins-x-gc-activities" cannot get deployments.apps in the namespace "jx"
```